name: main_portfolio_repo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.0.20

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



ai2 logo.png
DRT_pexels-philippedonn-1169754.jpg
events.webp
events_old.webp
explainable_AI.webp
gen_ai_med_teacher_pexels-cottonbro-7579829.jpg
heart question mark.webp
kaggle_health_hackathon.webp
kaggle_nature_hackathon.webp
lane_detection.jpg
reinforcement_learning.webp
strathclyde boat bulding old.jpg
strathclyde boat bulding.jpg
ST_A_bacteria_fluorescent.jpeg
things_i_learnt_pexels-singkham-178541-1108572.jpg
trad_ML.webp
train_game.webp
vision_transformer.webp
weather fourier series modelling.webp
words_full_stack.png

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/project1-nice-clear-light-bulbs-eujn90ms9da1bw9j.jpg
    - assets/project2-3cb45f6e59190e8213ce0a35394d0e11-nice.jpg
    - assets/project3-pexels-eberhardgross-443446.jpg
    - assets/project4-pexels-eberhardgross-443446.jpg
    - assets/project5-pexels-eberhardgross-1366919.jpg
    - assets/project6-pexels-eberhardgross-1624496.jpg
    - assets/project7-pexels-pixabay-33045.jpg
    - assets/project8-pexels-pixabay-33109.jpg
    - assets/project9-pexels-pixabay-60597.jpg
    - assets/project10-pexels-pixabay-326055.jpg
    - assets/project11-pexels-sohi-807598.jpg
    - assets/project12-pexels-thatguycraig000-1563355.jpg
    - assets/project13-pexels-vladalex94-1402787.jpg
    - assets/ai2 logo.png
    - assets/DRT_pexels-philippedonn-1169754.jpg
    - assets/events.webp
    - assets/events_old.webp
    - assets/explainable_AI.webp
    - assets/gen_ai_med_teacher_pexels-cottonbro-7579829.jpg
    - assets/heart question mark.webp
    - assets/kaggle_health_hackathon.webp
    - assets/kaggle_nature_hackathon.webp
    - assets/lane_detection.jpg
    - assets/reinforcement_learning.webp
    - assets/strathclyde boat bulding old.jpg
    - assets/strathclyde boat bulding.jpg
    - assets/ST_A_bacteria_fluorescent.jpeg
    - assets/things_i_learnt_pexels-singkham-178541-1108572.jpg
    - assets/trad_ML.webp
    - assets/train_game.webp
    - assets/vision_transformer.webp
    - assets/weather fourier series modelling.webp
    - assets/words_full_stack.png
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg
    # Add more assets here

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
